apiVersion: v1
kind: Service
metadata:
    name: http
spec:
    selector:
        app: http
    type: NodePort
    ports:
    -   nodePort: 31234
        port: 8090
        protocol: TCP
        targetPort: 8090